package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

/**
 * AdministrateurId generated by hbm2java
 */
public class AdministrateurId implements java.io.Serializable {

	private int idpersonne;
	private int idadmin;

	public AdministrateurId() {
	}

	public AdministrateurId(int idpersonne, int idadmin) {
		this.idpersonne = idpersonne;
		this.idadmin = idadmin;
	}

	public int getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	public int getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(int idadmin) {
		this.idadmin = idadmin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdministrateurId))
			return false;
		AdministrateurId castOther = (AdministrateurId) other;

		return (this.getIdpersonne() == castOther.getIdpersonne()) && (this.getIdadmin() == castOther.getIdadmin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpersonne();
		result = 37 * result + this.getIdadmin();
		return result;
	}

}
