package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

/**
 * Administrateur generated by hbm2java
 */
public class Administrateur implements java.io.Serializable {

	private AdministrateurId id;
	private Personne personne;

	public Administrateur() {
	}

	public Administrateur(AdministrateurId id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public AdministrateurId getId() {
		return this.id;
	}

	public void setId(AdministrateurId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

}
