package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private ClientId id;
	private Personne personne;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);
	private Set<Voiture> voitures = new HashSet<Voiture>(0);

	public Client() {
	}

	public Client(ClientId id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public Client(ClientId id, Personne personne, Set<Reservation> reservations, Set<Voiture> voitures) {
		this.id = id;
		this.personne = personne;
		this.reservations = reservations;
		this.voitures = voitures;
	}

	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

	public Set<Voiture> getVoitures() {
		return this.voitures;
	}

	public void setVoitures(Set<Voiture> voitures) {
		this.voitures = voitures;
	}

}
