package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

/**
 * ClientId generated by hbm2java
 */
public class ClientId implements java.io.Serializable {

	private int idpersonne;
	private int idclient;

	public ClientId() {
	}

	public ClientId(int idpersonne, int idclient) {
		this.idpersonne = idpersonne;
		this.idclient = idclient;
	}

	public int getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientId))
			return false;
		ClientId castOther = (ClientId) other;

		return (this.getIdpersonne() == castOther.getIdpersonne()) && (this.getIdclient() == castOther.getIdclient());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpersonne();
		result = 37 * result + this.getIdclient();
		return result;
	}

}
