package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

/**
 * DepartementId generated by hbm2java
 */
public class DepartementId implements java.io.Serializable {

	private int idregion;
	private int iddepartement;

	public DepartementId() {
	}

	public DepartementId(int idregion, int iddepartement) {
		this.idregion = idregion;
		this.iddepartement = iddepartement;
	}

	public int getIdregion() {
		return this.idregion;
	}

	public void setIdregion(int idregion) {
		this.idregion = idregion;
	}

	public int getIddepartement() {
		return this.iddepartement;
	}

	public void setIddepartement(int iddepartement) {
		this.iddepartement = iddepartement;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepartementId))
			return false;
		DepartementId castOther = (DepartementId) other;

		return (this.getIdregion() == castOther.getIdregion())
				&& (this.getIddepartement() == castOther.getIddepartement());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdregion();
		result = 37 * result + this.getIddepartement();
		return result;
	}

}
