package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departement generated by hbm2java
 */
public class Departement implements java.io.Serializable {

	private DepartementId id;
	private Region region;
	private String nomdepartement;
	private Set<Parking> parkings = new HashSet<Parking>(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Departement() {
	}

	public Departement(DepartementId id, Region region) {
		this.id = id;
		this.region = region;
	}

	public Departement(DepartementId id, Region region, String nomdepartement, Set<Parking> parkings,
			Set<Reservation> reservations) {
		this.id = id;
		this.region = region;
		this.nomdepartement = nomdepartement;
		this.parkings = parkings;
		this.reservations = reservations;
	}

	public DepartementId getId() {
		return this.id;
	}

	public void setId(DepartementId id) {
		this.id = id;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public String getNomdepartement() {
		return this.nomdepartement;
	}

	public void setNomdepartement(String nomdepartement) {
		this.nomdepartement = nomdepartement;
	}

	public Set<Parking> getParkings() {
		return this.parkings;
	}

	public void setParkings(Set<Parking> parkings) {
		this.parkings = parkings;
	}

	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
