package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

/**
 * DetailslocationId generated by hbm2java
 */
public class DetailslocationId implements java.io.Serializable {

	private int idreservation;
	private int idparking;
	private int idplace;
	private int idlocation;

	public DetailslocationId() {
	}

	public DetailslocationId(int idreservation, int idparking, int idplace, int idlocation) {
		this.idreservation = idreservation;
		this.idparking = idparking;
		this.idplace = idplace;
		this.idlocation = idlocation;
	}

	public int getIdreservation() {
		return this.idreservation;
	}

	public void setIdreservation(int idreservation) {
		this.idreservation = idreservation;
	}

	public int getIdparking() {
		return this.idparking;
	}

	public void setIdparking(int idparking) {
		this.idparking = idparking;
	}

	public int getIdplace() {
		return this.idplace;
	}

	public void setIdplace(int idplace) {
		this.idplace = idplace;
	}

	public int getIdlocation() {
		return this.idlocation;
	}

	public void setIdlocation(int idlocation) {
		this.idlocation = idlocation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailslocationId))
			return false;
		DetailslocationId castOther = (DetailslocationId) other;

		return (this.getIdreservation() == castOther.getIdreservation())
				&& (this.getIdparking() == castOther.getIdparking()) && (this.getIdplace() == castOther.getIdplace())
				&& (this.getIdlocation() == castOther.getIdlocation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdreservation();
		result = 37 * result + this.getIdparking();
		result = 37 * result + this.getIdplace();
		result = 37 * result + this.getIdlocation();
		return result;
	}

}
