package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gerant generated by hbm2java
 */
public class Gerant implements java.io.Serializable {

	private GerantId id;
	private Horaire horaire;
	private Parking parking;
	private Personne personne;
	private Date dateembauche;
	private String code;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Gerant() {
	}

	public Gerant(GerantId id, Horaire horaire, Parking parking, Personne personne) {
		this.id = id;
		this.horaire = horaire;
		this.parking = parking;
		this.personne = personne;
	}

	public Gerant(GerantId id, Horaire horaire, Parking parking, Personne personne, Date dateembauche, String code,
			Set<Reservation> reservations) {
		this.id = id;
		this.horaire = horaire;
		this.parking = parking;
		this.personne = personne;
		this.dateembauche = dateembauche;
		this.code = code;
		this.reservations = reservations;
	}

	public GerantId getId() {
		return this.id;
	}

	public void setId(GerantId id) {
		this.id = id;
	}

	public Horaire getHoraire() {
		return this.horaire;
	}

	public void setHoraire(Horaire horaire) {
		this.horaire = horaire;
	}

	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public Date getDateembauche() {
		return this.dateembauche;
	}

	public void setDateembauche(Date dateembauche) {
		this.dateembauche = dateembauche;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
