package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Horaire generated by hbm2java
 */
public class Horaire implements java.io.Serializable {

	private int idhoraire;
	private String heuredebut;
	private String heurefin;
	private String jours;
	private Set<Gerant> gerants = new HashSet<Gerant>(0);

	public Horaire() {
	}

	public Horaire(int idhoraire) {
		this.idhoraire = idhoraire;
	}

	public Horaire(int idhoraire, String heuredebut, String heurefin, String jours, Set<Gerant> gerants) {
		this.idhoraire = idhoraire;
		this.heuredebut = heuredebut;
		this.heurefin = heurefin;
		this.jours = jours;
		this.gerants = gerants;
	}

	public int getIdhoraire() {
		return this.idhoraire;
	}

	public void setIdhoraire(int idhoraire) {
		this.idhoraire = idhoraire;
	}

	public String getHeuredebut() {
		return this.heuredebut;
	}

	public void setHeuredebut(String heuredebut) {
		this.heuredebut = heuredebut;
	}

	public String getHeurefin() {
		return this.heurefin;
	}

	public void setHeurefin(String heurefin) {
		this.heurefin = heurefin;
	}

	public String getJours() {
		return this.jours;
	}

	public void setJours(String jours) {
		this.jours = jours;
	}

	public Set<Gerant> getGerants() {
		return this.gerants;
	}

	public void setGerants(Set<Gerant> gerants) {
		this.gerants = gerants;
	}

}
