package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Parking generated by hbm2java
 */
public class Parking implements java.io.Serializable {

	private int idparking;
	private Departement departement;
	private String email;
	private String tetephone;
	private Integer nombreplace;
	private String heureoverture;
	private String heurefermeture;
	private Integer nombregerant;
	private String etat;
	private Set<Statistiques> statistiqueses = new HashSet<Statistiques>(0);
	private Set<Gerant> gerants = new HashSet<Gerant>(0);
	private Set<Place> places = new HashSet<Place>(0);

	public Parking() {
	}

	public Parking(int idparking, Departement departement) {
		this.idparking = idparking;
		this.departement = departement;
	}

	public Parking(int idparking, Departement departement, String email, String tetephone, Integer nombreplace,
			String heureoverture, String heurefermeture, Integer nombregerant, String etat,
			Set<Statistiques> statistiqueses, Set<Gerant> gerants, Set<Place> places) {
		this.idparking = idparking;
		this.departement = departement;
		this.email = email;
		this.tetephone = tetephone;
		this.nombreplace = nombreplace;
		this.heureoverture = heureoverture;
		this.heurefermeture = heurefermeture;
		this.nombregerant = nombregerant;
		this.etat = etat;
		this.statistiqueses = statistiqueses;
		this.gerants = gerants;
		this.places = places;
	}

	public int getIdparking() {
		return this.idparking;
	}

	public void setIdparking(int idparking) {
		this.idparking = idparking;
	}

	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTetephone() {
		return this.tetephone;
	}

	public void setTetephone(String tetephone) {
		this.tetephone = tetephone;
	}

	public Integer getNombreplace() {
		return this.nombreplace;
	}

	public void setNombreplace(Integer nombreplace) {
		this.nombreplace = nombreplace;
	}

	public String getHeureoverture() {
		return this.heureoverture;
	}

	public void setHeureoverture(String heureoverture) {
		this.heureoverture = heureoverture;
	}

	public String getHeurefermeture() {
		return this.heurefermeture;
	}

	public void setHeurefermeture(String heurefermeture) {
		this.heurefermeture = heurefermeture;
	}

	public Integer getNombregerant() {
		return this.nombregerant;
	}

	public void setNombregerant(Integer nombregerant) {
		this.nombregerant = nombregerant;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Set<Statistiques> getStatistiqueses() {
		return this.statistiqueses;
	}

	public void setStatistiqueses(Set<Statistiques> statistiqueses) {
		this.statistiqueses = statistiqueses;
	}

	public Set<Gerant> getGerants() {
		return this.gerants;
	}

	public void setGerants(Set<Gerant> gerants) {
		this.gerants = gerants;
	}

	public Set<Place> getPlaces() {
		return this.places;
	}

	public void setPlaces(Set<Place> places) {
		this.places = places;
	}

}
