
package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Personne implements java.io.Serializable {

	private int idpersonne;
	private String nom;
	private String prenom;
	private String email;
	private String telephone;
	private String adresse;
	private String numerocarteidentite;
	private String profil;
	private String login;
	private String password;
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<Gerant> gerants = new HashSet<Gerant>(0);
	private Set<Administrateur> administrateurs = new HashSet<Administrateur>(0);

	public Personne() {
	}

	public Personne(int idpersonne, String nom, String email) {
		this.idpersonne = idpersonne;
		this.nom = nom;
		this.email = email;
	}

	public Personne(int idpersonne, String nom, String prenom, String email, String telephone, String adresse,
			String numerocarteidentite, String profil, String login, String password, Set<Client> clients,
			Set<Gerant> gerants, Set<Administrateur> administrateurs) {
		this.idpersonne = idpersonne;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.telephone = telephone;
		this.adresse = adresse;
		this.numerocarteidentite = numerocarteidentite;
		this.profil = profil;
		this.login = login;
		this.password = password;
		this.clients = clients;
		this.gerants = gerants;
		this.administrateurs = administrateurs;
	}

	public int getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getNumerocarteidentite() {
		return this.numerocarteidentite;
	}

	public void setNumerocarteidentite(String numerocarteidentite) {
		this.numerocarteidentite = numerocarteidentite;
	}

	public String getProfil() {
		return this.profil;
	}

	public void setProfil(String profil) {
		this.profil = profil;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	public Set<Gerant> getGerants() {
		return this.gerants;
	}

	public void setGerants(Set<Gerant> gerants) {
		this.gerants = gerants;
	}

	public Set<Administrateur> getAdministrateurs() {
		return this.administrateurs;
	}

	public void setAdministrateurs(Set<Administrateur> administrateurs) {
		this.administrateurs = administrateurs;
	}

}
