package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

/**
 * PlaceId generated by hbm2java
 */
public class PlaceId implements java.io.Serializable {

	private int idparking;
	private int idplace;

	public PlaceId() {
	}

	public PlaceId(int idparking, int idplace) {
		this.idparking = idparking;
		this.idplace = idplace;
	}

	public int getIdparking() {
		return this.idparking;
	}

	public void setIdparking(int idparking) {
		this.idparking = idparking;
	}

	public int getIdplace() {
		return this.idplace;
	}

	public void setIdplace(int idplace) {
		this.idplace = idplace;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaceId))
			return false;
		PlaceId castOther = (PlaceId) other;

		return (this.getIdparking() == castOther.getIdparking()) && (this.getIdplace() == castOther.getIdplace());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdparking();
		result = 37 * result + this.getIdplace();
		return result;
	}

}
