package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Place generated by hbm2java
 */
public class Place implements java.io.Serializable {

	private PlaceId id;
	private Parking parking;
	private String type;
	private String etat;
	private BigInteger prix;
	private Set<Detailslocation> detailslocations = new HashSet<Detailslocation>(0);

	public Place() {
	}

	public Place(PlaceId id, Parking parking) {
		this.id = id;
		this.parking = parking;
	}

	public Place(PlaceId id, Parking parking, String type, String etat, BigInteger prix,
			Set<Detailslocation> detailslocations) {
		this.id = id;
		this.parking = parking;
		this.type = type;
		this.etat = etat;
		this.prix = prix;
		this.detailslocations = detailslocations;
	}

	public PlaceId getId() {
		return this.id;
	}

	public void setId(PlaceId id) {
		this.id = id;
	}

	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public BigInteger getPrix() {
		return this.prix;
	}

	public void setPrix(BigInteger prix) {
		this.prix = prix;
	}

	public Set<Detailslocation> getDetailslocations() {
		return this.detailslocations;
	}

	public void setDetailslocations(Set<Detailslocation> detailslocations) {
		this.detailslocations = detailslocations;
	}

}
