package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private int idregion;
	private String nomregion;
	private Set<Departement> departements = new HashSet<Departement>(0);

	public Region() {
	}

	public Region(int idregion) {
		this.idregion = idregion;
	}

	public Region(int idregion, String nomregion, Set<Departement> departements) {
		this.idregion = idregion;
		this.nomregion = nomregion;
		this.departements = departements;
	}

	public int getIdregion() {
		return this.idregion;
	}

	public void setIdregion(int idregion) {
		this.idregion = idregion;
	}

	public String getNomregion() {
		return this.nomregion;
	}

	public void setNomregion(String nomregion) {
		this.nomregion = nomregion;
	}

	public Set<Departement> getDepartements() {
		return this.departements;
	}

	public void setDepartements(Set<Departement> departements) {
		this.departements = departements;
	}

}
