package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private int idreservation;
	private Client client;
	private Departement departement;
	private Gerant gerant;
	private Date datereservation;
	private String heurereservation;
	private String etat;
	private Set<Detailslocation> detailslocations = new HashSet<Detailslocation>(0);

	public Reservation() {
	}

	public Reservation(int idreservation, Client client, Departement departement, Gerant gerant) {
		this.idreservation = idreservation;
		this.client = client;
		this.departement = departement;
		this.gerant = gerant;
	}

	public Reservation(int idreservation, Client client, Departement departement, Gerant gerant, Date datereservation,
			String heurereservation, String etat, Set<Detailslocation> detailslocations) {
		this.idreservation = idreservation;
		this.client = client;
		this.departement = departement;
		this.gerant = gerant;
		this.datereservation = datereservation;
		this.heurereservation = heurereservation;
		this.etat = etat;
		this.detailslocations = detailslocations;
	}

	public int getIdreservation() {
		return this.idreservation;
	}

	public void setIdreservation(int idreservation) {
		this.idreservation = idreservation;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	public Gerant getGerant() {
		return this.gerant;
	}

	public void setGerant(Gerant gerant) {
		this.gerant = gerant;
	}

	public Date getDatereservation() {
		return this.datereservation;
	}

	public void setDatereservation(Date datereservation) {
		this.datereservation = datereservation;
	}

	public String getHeurereservation() {
		return this.heurereservation;
	}

	public void setHeurereservation(String heurereservation) {
		this.heurereservation = heurereservation;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Set<Detailslocation> getDetailslocations() {
		return this.detailslocations;
	}

	public void setDetailslocations(Set<Detailslocation> detailslocations) {
		this.detailslocations = detailslocations;
	}

}
