package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;

/**
 * Statistiques generated by hbm2java
 */
public class Statistiques implements java.io.Serializable {

	private int idstatistique;
	private Parking parking;
	private Integer nombrevoiturespresente;
	private String heureplusfrequentee;
	private Integer evolutionparking;
	private BigInteger chiffredAffaires;
	private BigInteger tauxdOccupation;

	public Statistiques() {
	}

	public Statistiques(int idstatistique, Parking parking) {
		this.idstatistique = idstatistique;
		this.parking = parking;
	}

	public Statistiques(int idstatistique, Parking parking, Integer nombrevoiturespresente, String heureplusfrequentee,
			Integer evolutionparking, BigInteger chiffredAffaires, BigInteger tauxdOccupation) {
		this.idstatistique = idstatistique;
		this.parking = parking;
		this.nombrevoiturespresente = nombrevoiturespresente;
		this.heureplusfrequentee = heureplusfrequentee;
		this.evolutionparking = evolutionparking;
		this.chiffredAffaires = chiffredAffaires;
		this.tauxdOccupation = tauxdOccupation;
	}

	public int getIdstatistique() {
		return this.idstatistique;
	}

	public void setIdstatistique(int idstatistique) {
		this.idstatistique = idstatistique;
	}

	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	public Integer getNombrevoiturespresente() {
		return this.nombrevoiturespresente;
	}

	public void setNombrevoiturespresente(Integer nombrevoiturespresente) {
		this.nombrevoiturespresente = nombrevoiturespresente;
	}

	public String getHeureplusfrequentee() {
		return this.heureplusfrequentee;
	}

	public void setHeureplusfrequentee(String heureplusfrequentee) {
		this.heureplusfrequentee = heureplusfrequentee;
	}

	public Integer getEvolutionparking() {
		return this.evolutionparking;
	}

	public void setEvolutionparking(Integer evolutionparking) {
		this.evolutionparking = evolutionparking;
	}

	public BigInteger getChiffredAffaires() {
		return this.chiffredAffaires;
	}

	public void setChiffredAffaires(BigInteger chiffredAffaires) {
		this.chiffredAffaires = chiffredAffaires;
	}

	public BigInteger getTauxdOccupation() {
		return this.tauxdOccupation;
	}

	public void setTauxdOccupation(BigInteger tauxdOccupation) {
		this.tauxdOccupation = tauxdOccupation;
	}

}
