package bdbeans;
// Generated 2 nov. 2022, 16:22:46 by Hibernate Tools 4.3.6.Final

/**
 * Voiture generated by hbm2java
 */
public class Voiture implements java.io.Serializable {

	private int idvoiture;
	private Client client;
	private String immatriculation;
	private String marque;
	private String model;
	private String serie;

	public Voiture() {
	}

	public Voiture(int idvoiture, Client client) {
		this.idvoiture = idvoiture;
		this.client = client;
	}

	public Voiture(int idvoiture, Client client, String immatriculation, String marque, String model, String serie) {
		this.idvoiture = idvoiture;
		this.client = client;
		this.immatriculation = immatriculation;
		this.marque = marque;
		this.model = model;
		this.serie = serie;
	}

	public int getIdvoiture() {
		return this.idvoiture;
	}

	public void setIdvoiture(int idvoiture) {
		this.idvoiture = idvoiture;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getImmatriculation() {
		return this.immatriculation;
	}

	public void setImmatriculation(String immatriculation) {
		this.immatriculation = immatriculation;
	}

	public String getMarque() {
		return this.marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

}
